- name: install and run mysql
  hosts: web
  become: yes
  tasks:
  - name: Install mysql
    ansible.builtin.dnf:
      name: mysql
      state: present
  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes