- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes



- name: Install and Run Nginx
  hosts: web
  become: yes  # Run commands as sudo
  tasks:
  - name: Update APT package cache
    ansible.builtin.apt:
    update_cache: yes

  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx
      state: present

  - name: Start Nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
