- name: Installing mysql DB
  hosts: web
  become: yes
  tasks:
  - name: Create a new database with name 'mysql'
    community.mysql.mysql_db: 
      name: MySQL-python
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock