- name: Conditions ansible
  hosts: web
  become: yes
  tasks:
    - name: checking whether user is available or not
      ansible.builtin.command: id KK
      register: USER
      ignore_errors: true

    - name: print user information
      ansible.builtin.debug:
        msg: "user info: {{USER}}"

    - name: User is there
      ansible.builtin.debug:
        msg: "Hey KK"