- name: default values
  hosts: web
  tasks: 
    - name: print a default value
      ansible.builtin.debug:
        msg: "Hello {{course | default ('KK') }}"

- name: upper case
  hosts: web
  vars:
    greeting: hi good morning
  tasks: 
    - name: print a value to upper case
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

- name: lower case
  hosts: web
  vars:
    greeting: Hi Good Evening
  tasks:
  - name: lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"