- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: Installing packages
    ansible.builtin.ddnf:
      name: "{{item}}"
      state: present
    loop:
     - nginx
     - git
     - postfix