- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: Installing packages
    ansible.builtin.dnf:
      name: " {{item.name}} "
      state: "{{item.state}}"
    loop:
     - { name: 'nginx', state: 'absent' }
     - { name: 'postfix', state: 'absent' }